run:
  timeout: 5m
  go: '1.21'

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - errcheck
    - gosimple
    - typecheck
    - deadcode
    - varcheck
    - structcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: favorite-colors-mcp

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
